### ISSUE TITLE
Working Directory should be generic, not local to your PC

### ISSUE THREAD

**Issue by Dragonlaird** [bert-laverman/CsSimConnect#1]
When I cloned the solution and built it, everything seemed to go well, until I attempted to execute it, when I received an error.

![image](https://user-images.githubusercontent.com/6785615/115910130-600bc100-a464-11eb-96e9-b74aa85e0843.png)

To fix this, simply change the Working Directory to a single full-stop character (e.g. "." without the quotes)
![image](https://user-images.githubusercontent.com/6785615/115910078-52563b80-a464-11eb-976f-777ad7f4bd6d.png)

This will assume the current folder to be correct

**Comment by bert-laverman** [comment]
Yes, I did that to get a predictable location for running it. Sorry.

**Comment by bert-laverman** [comment]
(Wrong button)

**Comment by bert-laverman** [comment]
Should be relative now.
