### ISSUE TITLE
Rakis Missing from nuget.org

### ISSUE THREAD

**Issue by BossOfGames** [bert-laverman/CsSimConnect#5]
It appears that the Rakis library is missing from Nuget. Can you add to the documentation where to get this library so Visual Studio doesn't throw compiler errors?

**Comment by PixelHunter88** [comment]
Yes, same issue here. 
Seems to be dissapeared at all, even big g does not know it.

**Comment by PixelHunter88** [comment]
I found it!
It's one of your other gitbhub repos.
https://github.com/bert-laverman/RakisUtil
Thank you Bert!

**Comment by mario-fehr** [comment]
ping @BossOfGames I think this is answered and can be closed.
